// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Package auto-generated by `reggen` containing data structure

package system_info_reg_pkg;

  // Address widths within the block
  parameter int BlockAw = 4;

  ////////////////////////////
  // Typedefs for registers //
  ////////////////////////////

  typedef struct packed {
    logic [31:0] d;
  } system_info_hw2reg_rtl_commit_hash_0_reg_t;

  typedef struct packed {
    logic [31:0] d;
  } system_info_hw2reg_rtl_commit_hash_1_reg_t;

  typedef struct packed {
    logic        d;
  } system_info_hw2reg_rtl_commit_dirty_reg_t;

  // HW -> register type
  typedef struct packed {
    system_info_hw2reg_rtl_commit_hash_0_reg_t rtl_commit_hash_0; // [64:33]
    system_info_hw2reg_rtl_commit_hash_1_reg_t rtl_commit_hash_1; // [32:1]
    system_info_hw2reg_rtl_commit_dirty_reg_t rtl_commit_dirty; // [0:0]
  } system_info_hw2reg_t;

  // Register offsets
  parameter logic [BlockAw-1:0] SYSTEM_INFO_RTL_COMMIT_HASH_0_OFFSET = 4'h 0;
  parameter logic [BlockAw-1:0] SYSTEM_INFO_RTL_COMMIT_HASH_1_OFFSET = 4'h 4;
  parameter logic [BlockAw-1:0] SYSTEM_INFO_RTL_COMMIT_DIRTY_OFFSET = 4'h 8;

  // Reset values for hwext registers and their fields
  parameter logic [31:0] SYSTEM_INFO_RTL_COMMIT_HASH_0_RESVAL = 32'h 0;
  parameter logic [31:0] SYSTEM_INFO_RTL_COMMIT_HASH_1_RESVAL = 32'h 0;
  parameter logic [0:0] SYSTEM_INFO_RTL_COMMIT_DIRTY_RESVAL = 1'h 1;
  parameter logic [0:0] SYSTEM_INFO_RTL_COMMIT_DIRTY_DIRTY_RESVAL = 1'h 1;

  // Register index
  typedef enum int {
    SYSTEM_INFO_RTL_COMMIT_HASH_0,
    SYSTEM_INFO_RTL_COMMIT_HASH_1,
    SYSTEM_INFO_RTL_COMMIT_DIRTY
  } system_info_id_e;

  // Register width information to check illegal writes
  parameter logic [3:0] SYSTEM_INFO_PERMIT [3] = '{
    4'b 1111, // index[0] SYSTEM_INFO_RTL_COMMIT_HASH_0
    4'b 1111, // index[1] SYSTEM_INFO_RTL_COMMIT_HASH_1
    4'b 0001  // index[2] SYSTEM_INFO_RTL_COMMIT_DIRTY
  };

endpackage
