// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// Register Top module auto-generated by `reggen`

`include "prim_assert.sv"

module system_info_reg_top (
  input clk_i,
  input rst_ni,
  // To HW
  output system_info_reg_pkg::system_info_reg2hw_t reg2hw, // Write
  input  system_info_reg_pkg::system_info_hw2reg_t hw2reg, // Read

  input  tlul_pkg::tl_h2d_t tl_i,
  output tlul_pkg::tl_d2h_t tl_o
);

  import system_info_reg_pkg::* ;

  localparam int AW = 6;
  localparam int DW = 32;
  localparam int DBW = DW/8;                    // Byte Width

  // register signals
  logic           reg_we;
  logic           reg_re;
  logic [AW-1:0]  reg_addr;
  logic [DW-1:0]  reg_wdata;
  logic [DBW-1:0] reg_be;
  logic [DW-1:0]  reg_rdata;
  logic           reg_error;

  logic          addrmiss, wr_err;

  logic [DW-1:0] reg_rdata_next;
  logic reg_busy;

  tlul_pkg::tl_h2d_t tl_reg_h2d;
  tlul_pkg::tl_d2h_t tl_reg_d2h;


  // outgoing integrity generation
  tlul_pkg::tl_d2h_t tl_o_pre;
  tlul_rsp_intg_gen #(
    .EnableRspIntgGen(0),
    .EnableDataIntgGen(0)
  ) u_rsp_intg_gen (
    .tl_i(tl_o_pre),
    .tl_o(tl_o)
  );

  assign tl_reg_h2d = tl_i;
  assign tl_o_pre   = tl_reg_d2h;

  tlul_adapter_reg #(
    .RegAw(AW),
    .RegDw(DW),
    .EnableDataIntgGen(0)
  ) u_reg_if (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),

    .tl_i (tl_reg_h2d),
    .tl_o (tl_reg_d2h),

    .en_ifetch_i(prim_mubi_pkg::MuBi4False),
    .intg_error_o(),

    .we_o    (reg_we),
    .re_o    (reg_re),
    .addr_o  (reg_addr),
    .wdata_o (reg_wdata),
    .be_o    (reg_be),
    .busy_i  (reg_busy),
    .rdata_i (reg_rdata),
    .error_i (reg_error)
  );

  // cdc oversampling signals

  assign reg_rdata = reg_rdata_next ;
  assign reg_error = addrmiss | wr_err;

  // Define SW related signals
  // Format: <reg>_<field>_{wd|we|qs}
  //        or <reg>_{wd|we|qs} if field == 1 or 0
  logic rtl_commit_hash_0_re;
  logic [31:0] rtl_commit_hash_0_qs;
  logic rtl_commit_hash_1_re;
  logic [31:0] rtl_commit_hash_1_qs;
  logic rtl_commit_dirty_re;
  logic rtl_commit_dirty_qs;
  logic system_frequency_re;
  logic [31:0] system_frequency_qs;
  logic gpio_info_re;
  logic [7:0] gpio_info_qs;
  logic uart_info_re;
  logic [7:0] uart_info_qs;
  logic i2c_info_re;
  logic [7:0] i2c_info_qs;
  logic spi_info_re;
  logic [7:0] spi_info_qs;
  logic dna_capture_we;
  logic dna_capture_wd;
  logic dna_re;
  logic dna_qs;
  logic mem_size_re;
  logic [31:0] mem_size_qs;
  logic hyperram_size_re;
  logic [31:0] hyperram_size_qs;
  logic hyperram_tag_size_re;
  logic [31:0] hyperram_tag_size_qs;

  // Register instances
  // R[rtl_commit_hash_0]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_rtl_commit_hash_0 (
    .re     (rtl_commit_hash_0_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.rtl_commit_hash_0.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (rtl_commit_hash_0_qs)
  );


  // R[rtl_commit_hash_1]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_rtl_commit_hash_1 (
    .re     (rtl_commit_hash_1_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.rtl_commit_hash_1.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (rtl_commit_hash_1_qs)
  );


  // R[rtl_commit_dirty]: V(True)
  prim_subreg_ext #(
    .DW    (1)
  ) u_rtl_commit_dirty (
    .re     (rtl_commit_dirty_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.rtl_commit_dirty.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (rtl_commit_dirty_qs)
  );


  // R[system_frequency]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_system_frequency (
    .re     (system_frequency_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.system_frequency.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (system_frequency_qs)
  );


  // R[gpio_info]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_gpio_info (
    .re     (gpio_info_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.gpio_info.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (gpio_info_qs)
  );


  // R[uart_info]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_uart_info (
    .re     (uart_info_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.uart_info.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (uart_info_qs)
  );


  // R[i2c_info]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_i2c_info (
    .re     (i2c_info_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.i2c_info.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (i2c_info_qs)
  );


  // R[spi_info]: V(True)
  prim_subreg_ext #(
    .DW    (8)
  ) u_spi_info (
    .re     (spi_info_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.spi_info.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (spi_info_qs)
  );


  // R[dna_capture]: V(True)
  logic dna_capture_qe;
  logic [0:0] dna_capture_flds_we;
  assign dna_capture_qe = &dna_capture_flds_we;
  prim_subreg_ext #(
    .DW    (1)
  ) u_dna_capture (
    .re     (1'b0),
    .we     (dna_capture_we),
    .wd     (dna_capture_wd),
    .d      ('0),
    .qre    (),
    .qe     (dna_capture_flds_we[0]),
    .q      (reg2hw.dna_capture.q),
    .ds     (),
    .qs     ()
  );
  assign reg2hw.dna_capture.qe = dna_capture_qe;


  // R[dna]: V(True)
  prim_subreg_ext #(
    .DW    (1)
  ) u_dna (
    .re     (dna_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.dna.d),
    .qre    (reg2hw.dna.re),
    .qe     (),
    .q      (reg2hw.dna.q),
    .ds     (),
    .qs     (dna_qs)
  );


  // R[mem_size]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_mem_size (
    .re     (mem_size_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.mem_size.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (mem_size_qs)
  );


  // R[hyperram_size]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_hyperram_size (
    .re     (hyperram_size_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.hyperram_size.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (hyperram_size_qs)
  );


  // R[hyperram_tag_size]: V(True)
  prim_subreg_ext #(
    .DW    (32)
  ) u_hyperram_tag_size (
    .re     (hyperram_tag_size_re),
    .we     (1'b0),
    .wd     ('0),
    .d      (hw2reg.hyperram_tag_size.d),
    .qre    (),
    .qe     (),
    .q      (),
    .ds     (),
    .qs     (hyperram_tag_size_qs)
  );



  logic [12:0] addr_hit;
  always_comb begin
    addr_hit = '0;
    addr_hit[ 0] = (reg_addr == SYSTEM_INFO_RTL_COMMIT_HASH_0_OFFSET);
    addr_hit[ 1] = (reg_addr == SYSTEM_INFO_RTL_COMMIT_HASH_1_OFFSET);
    addr_hit[ 2] = (reg_addr == SYSTEM_INFO_RTL_COMMIT_DIRTY_OFFSET);
    addr_hit[ 3] = (reg_addr == SYSTEM_INFO_SYSTEM_FREQUENCY_OFFSET);
    addr_hit[ 4] = (reg_addr == SYSTEM_INFO_GPIO_INFO_OFFSET);
    addr_hit[ 5] = (reg_addr == SYSTEM_INFO_UART_INFO_OFFSET);
    addr_hit[ 6] = (reg_addr == SYSTEM_INFO_I2C_INFO_OFFSET);
    addr_hit[ 7] = (reg_addr == SYSTEM_INFO_SPI_INFO_OFFSET);
    addr_hit[ 8] = (reg_addr == SYSTEM_INFO_DNA_CAPTURE_OFFSET);
    addr_hit[ 9] = (reg_addr == SYSTEM_INFO_DNA_OFFSET);
    addr_hit[10] = (reg_addr == SYSTEM_INFO_MEM_SIZE_OFFSET);
    addr_hit[11] = (reg_addr == SYSTEM_INFO_HYPERRAM_SIZE_OFFSET);
    addr_hit[12] = (reg_addr == SYSTEM_INFO_HYPERRAM_TAG_SIZE_OFFSET);
  end

  assign addrmiss = (reg_re || reg_we) ? ~|addr_hit : 1'b0 ;

  // Check sub-word write is permitted
  always_comb begin
    wr_err = (reg_we &
              ((addr_hit[ 0] & (|(SYSTEM_INFO_PERMIT[ 0] & ~reg_be))) |
               (addr_hit[ 1] & (|(SYSTEM_INFO_PERMIT[ 1] & ~reg_be))) |
               (addr_hit[ 2] & (|(SYSTEM_INFO_PERMIT[ 2] & ~reg_be))) |
               (addr_hit[ 3] & (|(SYSTEM_INFO_PERMIT[ 3] & ~reg_be))) |
               (addr_hit[ 4] & (|(SYSTEM_INFO_PERMIT[ 4] & ~reg_be))) |
               (addr_hit[ 5] & (|(SYSTEM_INFO_PERMIT[ 5] & ~reg_be))) |
               (addr_hit[ 6] & (|(SYSTEM_INFO_PERMIT[ 6] & ~reg_be))) |
               (addr_hit[ 7] & (|(SYSTEM_INFO_PERMIT[ 7] & ~reg_be))) |
               (addr_hit[ 8] & (|(SYSTEM_INFO_PERMIT[ 8] & ~reg_be))) |
               (addr_hit[ 9] & (|(SYSTEM_INFO_PERMIT[ 9] & ~reg_be))) |
               (addr_hit[10] & (|(SYSTEM_INFO_PERMIT[10] & ~reg_be))) |
               (addr_hit[11] & (|(SYSTEM_INFO_PERMIT[11] & ~reg_be))) |
               (addr_hit[12] & (|(SYSTEM_INFO_PERMIT[12] & ~reg_be)))));
  end

  // Generate write-enables
  assign rtl_commit_hash_0_re = addr_hit[0] & reg_re & !reg_error;
  assign rtl_commit_hash_1_re = addr_hit[1] & reg_re & !reg_error;
  assign rtl_commit_dirty_re = addr_hit[2] & reg_re & !reg_error;
  assign system_frequency_re = addr_hit[3] & reg_re & !reg_error;
  assign gpio_info_re = addr_hit[4] & reg_re & !reg_error;
  assign uart_info_re = addr_hit[5] & reg_re & !reg_error;
  assign i2c_info_re = addr_hit[6] & reg_re & !reg_error;
  assign spi_info_re = addr_hit[7] & reg_re & !reg_error;
  assign dna_capture_we = addr_hit[8] & reg_we & !reg_error;

  assign dna_capture_wd = reg_wdata[0];
  assign dna_re = addr_hit[9] & reg_re & !reg_error;
  assign mem_size_re = addr_hit[10] & reg_re & !reg_error;
  assign hyperram_size_re = addr_hit[11] & reg_re & !reg_error;
  assign hyperram_tag_size_re = addr_hit[12] & reg_re & !reg_error;

  // Read data return
  always_comb begin
    reg_rdata_next = '0;
    unique case (1'b1)
      addr_hit[0]: begin
        reg_rdata_next[31:0] = rtl_commit_hash_0_qs;
      end

      addr_hit[1]: begin
        reg_rdata_next[31:0] = rtl_commit_hash_1_qs;
      end

      addr_hit[2]: begin
        reg_rdata_next[0] = rtl_commit_dirty_qs;
      end

      addr_hit[3]: begin
        reg_rdata_next[31:0] = system_frequency_qs;
      end

      addr_hit[4]: begin
        reg_rdata_next[7:0] = gpio_info_qs;
      end

      addr_hit[5]: begin
        reg_rdata_next[7:0] = uart_info_qs;
      end

      addr_hit[6]: begin
        reg_rdata_next[7:0] = i2c_info_qs;
      end

      addr_hit[7]: begin
        reg_rdata_next[7:0] = spi_info_qs;
      end

      addr_hit[8]: begin
        reg_rdata_next[0] = '0;
      end

      addr_hit[9]: begin
        reg_rdata_next[0] = dna_qs;
      end

      addr_hit[10]: begin
        reg_rdata_next[31:0] = mem_size_qs;
      end

      addr_hit[11]: begin
        reg_rdata_next[31:0] = hyperram_size_qs;
      end

      addr_hit[12]: begin
        reg_rdata_next[31:0] = hyperram_tag_size_qs;
      end

      default: begin
        reg_rdata_next = '1;
      end
    endcase
  end

  // shadow busy
  logic shadow_busy;
  assign shadow_busy = 1'b0;

  // register busy
  assign reg_busy = shadow_busy;

  // Unused signal tieoff

  // wdata / byte enable are not always fully used
  // add a blanket unused statement to handle lint waivers
  logic unused_wdata;
  logic unused_be;
  assign unused_wdata = ^reg_wdata;
  assign unused_be = ^reg_be;

  // Assertions for Register Interface
  `ASSERT_PULSE(wePulse, reg_we, clk_i, !rst_ni)
  `ASSERT_PULSE(rePulse, reg_re, clk_i, !rst_ni)

  `ASSERT(reAfterRv, $rose(reg_re || reg_we) |=> tl_o_pre.d_valid, clk_i, !rst_ni)

  `ASSERT(en2addrHit, (reg_we || reg_re) |-> $onehot0(addr_hit), clk_i, !rst_ni)

  // this is formulated as an assumption such that the FPV testbenches do disprove this
  // property by mistake
  //`ASSUME(reqParity, tl_reg_h2d.a_valid |-> tl_reg_h2d.a_user.chk_en == tlul_pkg::CheckDis)

endmodule
