// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_peri package generated by `tlgen.py` tool

package tl_peri_pkg;

  localparam logic [31:0] ADDR_SPACE_GPIO        = 32'h 80000000;
  localparam logic [31:0] ADDR_SPACE_PINMUX      = 32'h 80005000;
  localparam logic [31:0] ADDR_SPACE_RGBLED_CTRL = 32'h 80009000;
  localparam logic [31:0] ADDR_SPACE_HW_REV      = 32'h 8000a000;
  localparam logic [31:0] ADDR_SPACE_XADC        = 32'h 8000b000;
  localparam logic [31:0] ADDR_SPACE_SYSTEM_INFO = 32'h 8000c000;
  localparam logic [31:0] ADDR_SPACE_TIMER       = 32'h 80040000;
  localparam logic [31:0] ADDR_SPACE_PWM0        = 32'h 80001000;
  localparam logic [31:0] ADDR_SPACE_UART0       = 32'h 80100000;
  localparam logic [31:0] ADDR_SPACE_UART1       = 32'h 80101000;
  localparam logic [31:0] ADDR_SPACE_UART2       = 32'h 80102000;

  localparam logic [31:0] ADDR_MASK_GPIO        = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_PINMUX      = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_RGBLED_CTRL = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_HW_REV      = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_XADC        = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_SYSTEM_INFO = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_TIMER       = 32'h 0000ffff;
  localparam logic [31:0] ADDR_MASK_PWM0        = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_UART0       = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_UART1       = 32'h 00000fff;
  localparam logic [31:0] ADDR_MASK_UART2       = 32'h 00000fff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 11;

  typedef enum int {
    TlGpio = 0,
    TlPinmux = 1,
    TlRgbledCtrl = 2,
    TlHwRev = 3,
    TlXadc = 4,
    TlSystemInfo = 5,
    TlTimer = 6,
    TlPwm0 = 7,
    TlUart0 = 8,
    TlUart1 = 9,
    TlUart2 = 10
  } tl_device_e;

  typedef enum int {
    TlMain = 0
  } tl_host_e;

endpackage
